services:
  db:
    container_name: postgres
    image: postgres:14.19
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: t1
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d t1 -U ${DB_USERNAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db: