server:
  port: 8080

spring:
  application:
    name: t1
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: jdbc:postgresql://localhost:5432/t1
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    url: jdbc:postgresql://localhost:5432/t1
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  threads:
    virtual:
      enabled: true

app:
  auth:
    jwt:
      secret: ${JWT_SECRET}
      expirationMs: 3600000
    refreshToken:
      expirationMs: 604800000
      cleanupCron: 0 0 4 * * *
      cleanupDays: 30
  ranking:
      cron: 0 15 23 * * FRI
      basePoints: 40
      stepPoints: 2

