server:
  port: 8080

spring:
  application:
    name: elre7la
  datasource:
    url: jdbc:postgresql://localhost:5432/elre7la
    username: postgres
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    url: jdbc:postgresql://localhost:5432/elre7la
    user: postgres
    password: P@ssw0rd
  threads:
    virtual:
      enabled: true

app:
  auth:
    jwt:
      secret: 18b40f2d002fac200027ce885a23a5cbdd8b27ae2c890f44bf423340c44bb9ae
      expirationMs: 3600000
    refreshToken:
      expirationMs: 86400000
      cleanupCron: 0 0 4 * * *
      cleanupDays: 30