server:
  port: 8080

spring:
  application:
    name: t1
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: jdbc:postgresql://localhost:5432/t1
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:P@ssw0rd}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    url: jdbc:postgresql://localhost:5432/t1
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:P@ssw0rd}
  threads:
    virtual:
      enabled: true

app:
  auth:
    jwt:
      secret: ${JWT_SECRET:18b40f2d002fac200027ce885a23a5cbdd8b27ae2c890f44bf423340c44bb9ae}
      expirationMs: 3600000
    refreshToken:
      expirationMs: 604800000
      cleanupCron: 0 0 4 * * *
      cleanupDays: 30
  ranking:
      cron: 0 0 3 * * THU
      basePoints: 40
      stepPoints: 2

